

version: "3.7"
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: grocerydb
      MYSQL_USER: pradip
      MYSQL_PASSWORD: root@123
      MYSQL_ROOT_PASSWORD: root@123
    networks:
      - mynetwork

  api_service:
      build: .
      restart: always
      ports:
        - 8081:8081
      environment:
        - spring.datasource.url=jdbc:mysql://mysqldb:3306/grocerydb?allowPublicKeyRetrieval=true&useSSL=FALSE
      depends_on:
        - mysqldb
      volumes:
        - .m2:/root/.m2
      networks:
      - mynetwork
      - default
networks:
  mynetwork:
